'use strict';
/* Split i18n.js into per-language dictionaries so a page only downloads the
   language it renders. i18n.js stays the single source of truth; the generated
   files are committed artefacts produced by `npm run i18n:split` (also run by
   `npm run build`) and verified by tests/i18n-split.test.js. */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ROOT = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8');
const start = source.indexOf('var translations =');
const end = source.indexOf('function lang()');
if (start < 0 || end < 0) throw new Error('i18n.js dictionaries not found');
const dicts = vm.runInNewContext(source.slice(start, end) + ';({en:translations,ko:translationsKo})');
const banner = '/* Generated by scripts/split-i18n.js — edit i18n.js instead. */\n';
let changed = 0;
for (const lang of ['en', 'ko']) {
  const file = path.join(ROOT, 'i18n.' + lang + '.js');
  const body = banner + 'window.ETI18N_' + lang + ' = ' + JSON.stringify(dicts[lang], null, 1) + ';\n';
  const previous = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (previous !== body) { fs.writeFileSync(file, body); changed++; }
  console.log('i18n.' + lang + '.js: ' + Object.keys(dicts[lang]).length + ' keys, ' + Buffer.byteLength(body) + ' bytes');
}
console.log('Split dictionaries written (' + changed + ' updated).');
module.exports = { dicts };
